CREATE TABLE IF NOT EXISTS Channels (
	ID 			INTEGER PRIMARY KEY AUTOINCREMENT,
	ChannelName	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
	ID			INTEGER PRIMARY KEY AUTOINCREMENT,
	UserName	TEXT NOT NULL,
	DOC			TEXT NOT NULL,
	PFP			TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Messages (
	ID				INTEGER PRIMARY KEY AUTOINCREMENT,
	SenderID	INTEGER NOT NULL,
	ChannelID INTEGER NOT NULL,
	Content		TEXT NOT NULL,
	MessageDate		TEXT NOT NULL,

	FOREIGN KEY(SenderID) 	REFERENCES Users (ID),
	FOREIGN KEY(ChannelID) 	REFERENCES Channels (ID)
);

CREATE TABLE IF NOT EXISTS Whispers (
	ID					INTEGER PRIMARY KEY AUTOINCREMENT,
	SenderID 		INTEGER NOT NULL,
	RecipientID	INTEGER NOT NULL,
	ChannelID 	INTEGER NOT NULL,
	Content 		TEXT NOT NULL,
	WhisperDate			TEXT NOT NULL,

	FOREIGN KEY(SenderID) 		REFERENCES Users (ID),
	FOREIGN KEY(RecipientID) 	REFERENCES Users (ID),
	FOREIGN KEY(ChannelID) 		REFERENCES Channels (ID)
);

CREATE TABLE IF NOT EXISTS Friends (
	PersonID INTEGER NOT NULL,
	FriendID INTEGER NOT NULL,
	FOREIGN KEY(PersonID) REFERENCES Users (ID),
	FOREIGN KEY(FriendID) REFERENCES Users (ID)
);
